### PR TITLE
Change name everywhere

### PR DESCRIPTION
**Pull request by marksiemers**

### CODE REVIEW

**Review by faustinoaq — DISMISSED** [review]

**Review by elorest — COMMENTED** [review]
What about namespacing? That's all been removed still?

**Comment by marksiemers** [comment]
@elorest - That's a good question. @eliasjpr was taking the approach of extending `Spec` itself.

I'm not sure if that is the best approach or not.

**Comment by elorest** [comment]
Would it be best just to inherit from crystal spec but call it Garnet::Spec?

**Comment by marksiemers** [comment]
Any ideas on why this passes locally every time, and passes for master, but not in travis for this branch?

**Comment by elorest** [comment]
Not that error again! I'll look when I get home.

**Comment by marksiemers** [comment]
It is because the website is responsive, and it headless mode, I guess that means there is no nav-bar to click on.

**Comment by marksiemers** [comment]
@elorest @eliasjpr - See #5 if we want the name change, that can be merged into this branch, then this merged to master.

Or they can be merged separately. I'll probably add a release `0.1.1` and bump the version after everything is approved.

**Review by eliasjpr — APPROVED** [review]

**Review by elorest — APPROVED** [review]
👍

**Comment by marksiemers** [comment]
These changes were incorporated with #5

**Comment by marksiemers** [comment]
Just kidding, gotta merge both PRs

**Pull request merged**
